name: calc_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  provider: ^6.1.2
  flutter_speed_dial: ^7.0.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

